### ISSUE TITLE
What to do when using Named Routes?

### ISSUE THREAD

**Issue by hardiklakhalani** [londonappbrewery/bmi-calculator-flutter#19]
main.dart
` initialRoute: '/',
        routes: {
          '/': (context) => InputPage(),
          '/results': (context) => ResultPage(),
        }`

input_page.dart
`BottomButton(
              buttonTitle: 'CALCULATE',
              onTap: () {
                CalculatorBrain calc =
                    CalculatorBrain(height: height, weight: weight);
                Navigator.pushNamed(context, '/results');
              },
            ),`

How do we pass properties to _ResultPage()_ ?

**Comment by sanchitpasricha** [comment]
After '/results' comma and add lines below
 **arguments**: Results_page(
                    bmiResult: calc.calculateBMI(),
                    result: calc.getResult(),
                    suggestion: calc.getSuggestion(),
                ),
