### ISSUE TITLE
No option in Android Studio [Latest Version] to Remove widget using ALT+Enter

### ISSUE THREAD

**Issue by Rajchowdhury420** [londonappbrewery/bmi-calculator-flutter#3]
I am Using Latest Android Studio in Linux & when i try to remove the widget called "Gesture Detector by hitting ALT+ENTER , there is no such option as remove widget except that other options are showing such as wrap up , swap with parent , Wrap with Container etc... i'm stuck in Midlle Please Help me out mam !!

**Comment by NGOCHOABUI** [comment]
You can use replace widget with its children.

**Comment by Rajchowdhury420** [comment]
thanks !
